---
- name: Development Server
  hosts: local
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - foreman
    - pm2
    - remoterepos
    - images
    - swagger
    - integrationtest
    - postgresql
    - dell
  vars:
# branch of https://github.com/rackhd/rackhd to be used
    - branch: "master"
