---
- name: Development Server
  hosts: local
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node-legacy
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - foreman
    - remoterepos
    - images
    - swagger
    - integrationtest
    - postgresql
  vars:
# branch of https://github.com/rackhd/rackhd to be used
    - branch: "master"
# version of Node.js to use
    - node_version: "0.10.41"
