#!/bin/bash

###########################################
# Build debian packages
###########################################

set -e
set -x

wget https://raw.githubusercontent.com/RackHD/RackHD/master/packer/ansible/roles/monorail/files/config.json  -O config.json

debuild --no-tgz-check -us -uc 

