# Copyright 2016, EMC, Inc.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Boot 2 Docker
    config.vm.define "b2d" do |target|
        target.vm.box = "dduportal/boot2docker"
        target.vm.box_version = "1.10.0"

        target.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 4
            v.customize ["modifyvm", :id, "--nictype1", "virtio"]
            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end

        target.vm.network "private_network", ip: "172.31.128.1", virtualbox__intnet: "closednet"

        target.vm.network "forwarded_port", guest: 27017, host: 27017, id: "Mongo DB"
        target.vm.network "forwarded_port", guest: 15672, host: 15672, id: "RabbitMQ Management"
        target.vm.network "forwarded_port", guest: 5672, host: 5672, id: "RabbitMQ AMQP"

        target.vm.network "forwarded_port", guest: 9080, host: 9080, id: "RackHD Southbound API"
        target.vm.network "forwarded_port", guest: 9090, host: 9090, id: "RackHD Northbound API"
        target.vm.network "forwarded_port", guest: 9100, host: 9100, id: "RackHD WebSocket Server"

        target.vm.network "forwarded_port", guest: 5601, host: 5601, id: "Kibana UI"
        target.vm.network "forwarded_port", guest: 9200, host: 9200, id: "Elasticsearch REST API"
        target.vm.network "forwarded_port", guest: 9300, host: 9300, id: "Elasticsearch Native"

        target.vm.synced_folder "..", "/RackHD"
        target.vm.synced_folder '.', '/vagrant', disabled: true
        # target.vm.synced_folder ".", Dir.pwd, disabled: true

        target.vm.provision :shell, inline: <<-SHELL
          sudo /etc/init.d/docker restart
          sudo cp -r /var/lib/boot2docker/tls /RackHD/docker/
        SHELL
    end
end
