version: '2'

services:
  consul:
    image: consul:0.7.5
    # NOTE: for additional nodes, add "-join <ip of primary> make sure the encrypt values match"
    #command: agent -server -ui -bind ${HOST_IP} -client 0.0.0.0 -log-level "info" -encrypt "Av0SYCoqCn8+jocR9EClTg=="
    command: agent -server -ui -bind ${HOST_IP} -client 0.0.0.0 -log-level "info"
    restart: always
    network_mode: "host"
    ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "53:53"
    # uncoment the line below to persist/reuse data after container is destroyed
    #volumes:
    #- /var/consul/data:/consul/data
    mem_limit: 512m
    environment:
      # for secondary node set bootstrap to false
      CONSUL_LOCAL_CONFIG: '{"bootstrap": true, "enable_syslog": false, "verify_server_hostname": false, "verify_incoming": false, "verify_outgoing": false }'

  gateway:
    container_name: gateway
    image: rackhd/gateway:latest
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46020:46020
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    mem_limit: 512m
    environment:
    - "GATEWAY_HOST=${HOST_IP}"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  device-discovery:
    container_name: device-discovery
    image: rackhd/device-discovery:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46002:46002
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss228k

  dell-server-action:
    container_name: dell-server-action
    image: rackhd/dell-server-action:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46007:46007
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  dell-chassis-inventory:
    container_name: dell-chassis-inventory
    image: rackhd/dell-chassis-inventory:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46001:46001
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-inventory:
    container_name: dell-server-inventory
    image: rackhd/dell-server-inventory:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46011:46011
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-configuration-profile:
    container_name: dell-server-configuration-profile
    image: rackhd/dell-server-configuration-profile:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46018:46018
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    privileged: true
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-firmwareupdate:
    container_name: dell-server-firmwareupdate
    image: rackhd/dell-server-firmwareupdate:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46010:46010
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    privileged: true
    #volumes:
    #- /var/log/dell:/var/log/dell
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  virtualnetwork:
    container_name: virtualnetwork
    image: rackhd/virtualnetwork:${TAG}
    depends_on:
    - consul
    - postgresql
    network_mode: "host"
    ports:
    - 46016:46016
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl/
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  virtualidentity:
    container_name: virtualidentity
    image: rackhd/virtualidentity:${TAG}
    depends_on:
    - consul
    - postgresql
    network_mode: "host"
    ports:
    - 46015:46015
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  dell-powerthermal-monitoring:
    container_name: dell-powerthermal-monitoring
    image: rackhd/dell-powerthermal-monitoring:${TAG}
    depends_on:
    - consul
    network_mode: "host"
    ports:
    - 46019:46019
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    volumes:
    - /var/log/dell/:/var/log/dell/
    - /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  postgresql:
    container_name: postgresql
    image: postgres:9.6.1-alpine
    ports:
    - 5433:5432
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=Dell123$$
