#!/bin/bash

# Copyright 2015, EMC, Inc.

set -e

SERVICES=("on-http" "on-taskgraph" "on-dhcp-proxy" "on-tftp" "on-syslog" "rackhd")

#############################################
# Copy the PXE image and micro kernel from bintray 
#############################################
copy_RackHD_static_bins(){
    echo "[INFO] Will Copy static files, it will take a while"
    mkdir -p /var/renasar/on-tftp/static/tftp
    cd /var/renasar/on-tftp/static/tftp

    for file in $(echo "\
        monorail.ipxe \
        monorail-undionly.kpxe \
        monorail-efi64-snponly.efi \
        monorail-efi32-snponly.efi");do
    wget --no-check-certificate "https://dl.bintray.com/rackhd/binary/ipxe/$file" 
    done

    mkdir -p /var/renasar/on-http/static/http/common
    cd /var/renasar/on-http/static/http/common

    for file in $(echo "\
        base.trusty.3.16.0-25-generic.squashfs.img \
        discovery.overlay.cpio.gz \
        initrd.img-3.16.0-25-generic \
        vmlinuz-3.16.0-25-generic");do
    wget --no-check-certificate "https://dl.bintray.com/rackhd/binary/builds/$file"
    done
}

#############################################
# Enable services: on-http, on-dhcp-proxy, on-tftp, on-syslog, on-taskgraph
#############################################
enable_services(){
    for i in ${SERVICES[@]}; do
        if [ -f /etc/default/${i} ];then
            echo "${i} is enabled"
        else
            touch /etc/default/${i}
        fi
    done
}

copy_RackHD_static_bins
enable_services

