#!/bin/bash

# Copyright 2016, DELL EMC, Inc.

set -e

#############################################
# Copy the PXE image and micro kernel from bintray 
#############################################
copy_RackHD_static_bins(){
    echo "[INFO] Will Copy static files, it will take a while"
    mkdir -p /var/renasar/on-tftp/static/tftp
    cd /var/renasar/on-tftp/static/tftp

    for file in $(echo "\
        monorail.ipxe \
        monorail-undionly.kpxe \
        monorail-efi64-snponly.efi \
        monorail-efi32-snponly.efi");do
    wget --no-check-certificate "https://dl.bintray.com/rackhd/binary/ipxe/$file" 
    done

    mkdir -p /var/renasar/on-http/static/http/common
    cd /var/renasar/on-http/static/http/common

    for file in $(echo "\
        base.trusty.3.16.0-25-generic.squashfs.img \
        discovery.overlay.cpio.gz \
        initrd.img-3.16.0-25-generic \
        vmlinuz-3.16.0-25-generic");do
    wget --no-check-certificate "https://dl.bintray.com/rackhd/binary/builds/$file"
    done
}

copy_RackHD_static_bins
