---
- name: set HTTP static directory for RackHD
  set_fact: http_static_directory="/var/renasar/on-http/static/http"

- name: set TFTP static directory for RackHD
  set_fact: tftp_static_directory="/var/renasar/on-tftp/static/tftp"



- name: Update git repos with latest
  shell: git fetch --all --prune
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-imagebuilder"

- name: Reset to the mater branch by default
  shell: git reset --hard master
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-imagebuilder"


- name: Reset to the branch specified
  shell: git reset --hard {{ branch }}
  when: branch is defined
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-imagebuilder"

- name: Clean the on-imagebuilder artifact folder 
  shell: rm /tmp/on-imagebuilder -rf
  sudo:  yes

- name: Build the overlay FS artifacts(kernel/overlay/iPXE/syslinux)
  shell:  ./build_all.sh
  args:
    chdir: "{{ ansible_env.HOME }}/src/on-imagebuilder"
  sudo: yes

- file: path="{{ http_static_directory }}/common" state=directory
        owner="{{ ansible_env.USER }}" mode=0755
  sudo: yes

- file: path="{{ tftp_static_directory }}" state=directory
        owner="{{ ansible_env.USER }}" mode=0755
  sudo: yes


- name: set on-imagebuilder artifacts location
  set_fact: artifacts_dir="/tmp/on-imagebuilder/"


- name: moving microkernel and overlays files to http static folder
  shell: cp {{artifacts_dir}}/builds/{{ item }} {{ http_static_directory }}/common/
  with_items:
  - base.*.squashfs.img
  - discovery.overlay.cpio.gz
  - initrd.img-*
  - vmlinuz-*

- name: moving  bootloaders to tftp static folder
  copy:    src= {{artifacts_dir}}/ipxe/{{ item }}
           dest={{ tftp_static_directory }}{{ item }}
  with_items:
   - monorail.ipxe
   - monorail-undionly.kpxe
   - monorail-efi32-snponly.efi
   - monorail-efi64-snponly.efi

- name: moving the syslinux bootloader to syslinux static folder
  copy:   src= {{artifacts_dir}}/syslinux/{{ item }}
          dest="{{ tftp_static_directory }}/{{ item }}"
  with_items:
   - undionly.kkpxe
