---
# We are essentially re-creating the monorail.json file
# as yaml, and then dumping it out as json in the template.
# There are other methods just as providing a source filename to lay
# This method provides an advantage of exposing all of the monorail
# settings as variables to the rest of the role. Additionaly, in a
# production environment, the shared keys and secrets will end up
# in a vault.

monorail:
  CIDRNet: "172.31.128.0/22"
  amqp: "amqp://localhost"
  apiServerAddress: "172.31.128.1"
  apiServerPort: 9080
  broadcastaddr: "172.31.131.255"
  dhcpGateway: "172.31.128.1"
  dhcpProxyBindAddress: "172.31.128.1"
  dhcpProxyBindPort: 4011
  dhcpSubnetMask: "255.255.252.0"
  httpEndpoints:
    - address: "0.0.0.0"
      port: 8080
      httpsEnabled: false
      proxiesEnabled: true
      authEnabled: false
      routers: "northbound-api-router"
    - address: "0.0.0.0"
      port: 8443
      httpsEnabled: true
      proxiesEnabled: true
      authEnabled: true
      routers: "northbound-api-router"
    - address: "172.31.128.1"
      port: 9080
      httpsEnabled: false
      proxiesEnabled: true
      authEnabled: false
      routers: "southbound-api-router"
  httpDocsRoot: "./build/apidoc"
  httpFileServiceRoot: "./static/files"
  httpFileServiceType: "FileSystem"
  httpProxies:
    - localPath: "/coreos"
      server: "http://stable.release.core-os.net"
      remotePath: "/amd64-usr"
  httpStaticRoot: "/opt/monorail/static/http"
  minLogLevel: 2
  authUsername: "admin"
  authPasswordHash: "KcBN9YobNV0wdux8h0fKNqi4uoKCgGl/j8c6YGlG7iA0PB3P9ojbmANGhDlcSBE0iOTIsYsGbtSsbqP4wvsVcw=="
  authPasswordSalt: "zlxkgxjvcFwm0M8sWaGojh25qNYO8tuNWUMN4xKPH93PidwkCAvaX2JItLA3p7BSCWIzkw4GwWuezoMvKf3UXg=="
  authTokenSecret: "RackHDRocks!"
  authTokenExpireIn: 86400
  mongo: "mongodb://localhost/pxe"
  sharedKey: "qxfO2D3tIJsZACu7UA6Fbw0avowo8r79ALzn+WeuC8M="
  statsd: "127.0.0.1:8125"
  subnetmask: "255.255.252.0"
  syslogBindAddress: "172.31.128.1"
  syslogBindPort: 514
  tftpBindAddress: "172.31.128.1"
  tftpBindPort: 69
  tftpRoot: "./static/tftp"

rackhd_services:
  - on-http
  - on-dhcp-proxy
  - on-taskgraph
  - on-tftp
